#!/bin/sh
sudo service unicorn_otterhiverails stop
git pull origin master
RAILS_ENV=production be rake db:migrate
RAILS_ENV=production assets:clean
RAILS_ENV=production assets:precompile
sudo service unicorn_otterhiverails start
