#!/bin/sh
sudo service unicorn_otterhiverails stop
git pull origin master
RAILS_ENV=production bundle exec rake db:migrate
RAILS_ENV=production bundle exec rake assets:clean
RAILS_ENV=production bundle exec rake assets:precompile
sudo service unicorn_otterhiverails start
